In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# dimention of an array
print(a.ndim)
b.ndim

1


2

In [9]:
# shape of an array
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
# data type in an array
# by default array is stored in 64bits
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

In [13]:
# allocating specific size in case of a small array
a1 = np.array([1,2,3], dtype = 'int16')

In [15]:
# it is 16bit now
a1.dtype

dtype('int16')

In [18]:
# Size of an array
# a is an 64bit array it will take 8 bytes of space 
a.itemsize

8

In [17]:
# as we specified the bit size to 16bit
# the memory size becomes 2 bytes
a1.itemsize

2

In [20]:
# total memory consumed by all the elements
a.nbytes

24

In [3]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
d.shape

(2, 7)

In [8]:
# extract an element [row,column]
# both row and column index starts with zero
d[0,4]

5

In [25]:
# using negative index
# remember negative index starts at one
d[1,-2]

13

In [13]:
# extract with a range
# remember ending index one less or index staring with 1
d[1,0:3]

array([ 8,  9, 10])

In [15]:
# extract a row
d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# extract a column
d[:,1]

array([2, 9])

In [22]:
# stepwise extract [start index:end index:stepsize]
d[1,1:6:2]

array([ 9, 11, 13])

In [21]:
# last action with negative end index
d[1,1:-1:2]

array([ 9, 11, 13])

In [46]:
# replacing an element
d[1,3] = 20
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 20, 12, 13, 14]])

In [48]:
# replacing a column
d[:,3] = 5
d

array([[ 1,  2,  3,  5,  5,  6,  7],
       [ 8,  9, 10,  5, 12, 13, 14]])

In [50]:
# with different number
d[:,4] = [1,2]
d

array([[ 1,  2,  3,  5,  1,  6,  7],
       [ 8,  9, 10,  5,  2, 13, 14]])

## 3D array

In [52]:
# 3D array
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
e

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [54]:
# extract an element [set,row,column]
e[1,0,1]

6

In [55]:
# extract multiple elements
e[:,0,:]

array([[1, 2],
       [5, 6]])

In [58]:
e[:,1,0]

array([3, 7])

In [59]:
# replace an element
e[1,1,0] = 9
e

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [9, 8]]])

In [61]:
# replacing a column
e[1,:,1] = [10,10]
e

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 10],
        [ 9, 10]]])

In [62]:
# replacing a row
# shape of the assigning array must be same
e[:,1,] = [[15,15],[14,14]]
e

array([[[ 1,  2],
        [15, 15]],

       [[ 5, 10],
        [14, 14]]])

## Initializing different types of arrays

In [63]:
# all 0s matrix
# single dimension or vector
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
# 2D array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# 3D array
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
# 4D array
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [68]:
# all 1s matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
# we can specify the datatype as well
np.ones((2,4), dtype = 'int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [70]:
# any other number
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [71]:
# like other array - uses the shape of an existing array
np.full_like(d,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [73]:
# using full
np.full(d.shape,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [74]:
# matrix of random decimal numbers (shape)
np.random.rand(4,2)

array([[0.10244694, 0.3431875 ],
       [0.53503457, 0.21478823],
       [0.92032005, 0.94580773],
       [0.37455208, 0.30087688]])

In [76]:
# using shape of an existing array
np.random.random_sample(d.shape)

array([[0.91402333, 0.48302237, 0.62662517, 0.79520072, 0.38722704,
        0.11469399, 0.4207297 ],
       [0.31721758, 0.82254893, 0.61843728, 0.55987326, 0.30091646,
        0.94085786, 0.85422623]])

In [79]:
# random number with integer values
# if you don't specify a size, it will print single digit
np.random.randint(7)

4

In [81]:
# with size
# remember 7 is the upper limit and excluded
# lower limit is 0
np.random.randint(7, size = (3,3))

array([[5, 6, 1],
       [4, 1, 5],
       [0, 1, 0]])

In [85]:
# with a range
np.random.randint(-4,7, size = (3,3))

array([[-1, -2, -2],
       [-2, -3,  5],
       [ 6, -4, -3]])

In [86]:
# identity matrix - a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
# repeat an array
arr = np.array([[4,5,6]])
r1 = np.repeat(arr, 3 , axis = 0)
print(r1)

[[4 5 6]
 [4 5 6]
 [4 5 6]]


## Build the following matrix

<img src="Assignment 1.png" />

In [90]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [93]:
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Careful when copying arrays

In [94]:
y = np.array([1,2,3])
z = y
z[1] = 100
print(z)
# only changed element in z but same happened to y as well
print(y)

[  1 100   3]
[  1 100   3]


In [95]:
w = np.array([1,2,3])
x = w.copy()
print(x)
x[1] = 99
print(x)
print(w)

[1 2 3]
[ 1 99  3]
[1 2 3]


## Mathematical operations

In [96]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [100]:
# elementwise mathematical operations
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [101]:
b = np.array([4,5,6])
c = np.array([7,8,9])
print(b+c)

[11 13 15]


In [102]:
# square
c**2

array([49, 64, 81])

In [105]:
# sine and cosine operation
print(np.sin(c))
print(np.cos(b))

[0.6569866  0.98935825 0.41211849]
[-0.65364362  0.28366219  0.96017029]


## Linear Algebra

In [110]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [109]:
# dot product in 1D array
np.dot(a,3)

array([[3., 3., 3.],
       [3., 3., 3.]])

In [108]:
# dot product in 2D array
c = np.array([[1, 0], [0, 1]])
d = np.array([[4, 1], [2, 2]])
np.dot(c,d)

array([[4, 1],
       [2, 2]])

In [114]:
# power
from numpy.linalg import matrix_power
matrix_power(d,3)


array([[84, 30],
       [60, 24]])

## Statistics

In [115]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
# min
np.min(stats)

1

In [118]:
# min - row wise
np.min(stats, axis = 1)

array([1, 4])

In [119]:
# min - column wise
np.min(stats, axis = 0)

array([1, 2, 3])

In [121]:
# max - axis can be used
np.max(stats)

6

In [122]:
# sum
np.sum(stats)

21

## Reorganising Arrays

In [124]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [128]:
before.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
# reshape values must fit all the elements
before.reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [134]:
# vertical stacking of vectors
# both the shapes must be same
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.vstack([v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [142]:
# horinzontal stacking
# row shape must be same
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2,h1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

## Miscellaneous

In [148]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
print(filedata)
# as int
filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and Advanced Indexing

In [150]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [152]:
# index of true values
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [153]:
# column wise if any value is more than 50 True returned
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [155]:
# in a column if all the values are more than 50 then True returned
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [156]:
# in case of rows
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [157]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [158]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])